#!/usr/bin/env bash

export SPARK_MASTER_HOST=spark-master
export SPARK_MASTER_PORT=7077
export SPARK_MASTER_WEBUI_PORT=8080
export SPARK_LOCAL_DIRS=/tmp/spark
export SPARK_LOG_DIR=/opt/spark/logs
export SPARK_WORKER_MEMORY=2g
export SPARK_WORKER_CORES=2
export SPARK_EXECUTOR_MEMORY=2g
export SPARK_DRIVER_MEMORY=1g
export SPARK_RPC_AUTHENTICATION_ENABLED=no
export SPARK_RPC_ENCRYPTION_ENABLED=no
export SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
export SPARK_SSL_ENABLED=no
export SPARK_NO_DAEMONIZE=1
